### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by kingofwap** [J05HI/DeezLoadr#1]
May i know where it stores downloaded files in windows ?

**Comment by J05HI** [comment]
Yeah at the same location where the application is, in the DOWNLOADS dir :)

**Comment by kingofwap** [comment]
works like charm super work bro.
thanks

**Comment by MonkeyWrench123** [comment]
@J05HI Being a bit cheeky here . Any chance you can add an artist watchlist function - maybe an import from file with a list of current artists, so it will pick up on new releases, or just continue where it lost got to?

Also can you please add track number to the start of track, so it matches itunes format - For example
01 Train.mp3

You should add a donate link - probably gonna want to use bitcoin......

**Comment by J05HI** [comment]
@MonkeyWrench123
The project is in a really early stage.
I have many ideas but less time :(

Some things I've planned for the future:
- User interface
- Download path selection
- Filename configuration (with variables)
- Something like a playlist watcher which checks a playlist in a defined cycle and downloads new tracks (do you mean this?)
- Artist/Album/Playlist search
- List of most popular songs by country
- ...

Feel free to add other ideas :)

**Comment by J05HI** [comment]
@MonkeyWrench123 
I've added the track number to the beginning of the songs (like in iTunes)
Take a look at the latest release here: [https://github.com/J05HI/DeezLoadr/releases](https://github.com/J05HI/DeezLoadr/releases)

PS: I've added a donate link :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
