### ISSUE TITLE
[Improvement] Show error and/or fall back to highest possible quality if selected quality is not available

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#10]
Example URL: http://www.deezer.com/us/album/802835
Maximum quality uploaded is 320kbps.

I tried to download FLAC and it saved non-working, 2 KB FLAC file. 
Can you fix this to show error or fall back to highest possible quality?

**Comment by J05HI** [comment]
@FatKiwi
Normally it should fall back to the highest quality below.
I'll take a look at it :)

**Comment by azgul** [comment]
This is due to https://github.com/J05HI/DeezLoadr/issues/14 which I've fixed in https://github.com/J05HI/DeezLoadr/pull/15

**Comment by J05HI** [comment]
Fixed with [https://github.com/J05HI/DeezLoadr/pull/15](https://github.com/J05HI/DeezLoadr/pull/15)
