### ISSUE TITLE
Country restricted/hidden tracks

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#11]
Example URL: http://www.deezer.com/en/album/11102742 (probably works for USA)
Album API says DataException 800 (No Data) and 404 Page if I try to open it directly.
Tracks API works, some info might be useful: http://api.deezer.com/2.0/track/106466810

It is very possible the album is hidden for all countries, Tracks API says "readable": false,"

However, I can easily download it with another downloader, unfortunately 320kbps only as the app I used is not updated.

Can something be done for country restrictions?

**Comment by oO-u-Oo** [comment]
Try to download it from tidal, I have managed to download complete tidal albums that don't could be downloaded from deezer by restrictions.

**Comment by J05HI** [comment]
@FatKiwi @oO-u-Oo 
Okay that's strange.
I got an error too :(
Will take a look at it.

**Comment by FatKiwi** [comment]
It's missing from Tidal, otherwise I would. 👍 
Thanks for looking into it. Great job so far!

**Comment by J05HI** [comment]
@FatKiwi 
How do you know this album (http://www.deezer.com/en/album/11102742) exists?
Maby it doesn't because the api sais "DataException: no data"

**Comment by FatKiwi** [comment]
It does. You can check track API, I can also download with Sparx's downloader.
And this too: http://www.deezer.com/en/profile/791625825/loved

**Comment by J05HI** [comment]
Okay strange :(
Which downloader is this? Can you send me a link please :)

**Comment by FatKiwi** [comment]
Link: https://mega.nz/#F!WoVD3LyK!BNRUDzYmI9oSHPTJKWwSIQ

**Comment by J05HI** [comment]
@FatKiwi
Thx! Is it open source?

**Comment by FatKiwi** [comment]
It's java, so yes. You can easily decompile jar. Not sure if you know java though. Don't waste your time on it for now, I believe it's problem with the track. Will report soon if VPN worked.

**Comment by FatKiwi** [comment]
Good news is country restricted tracks work perfectly. So it must be the case with this specific track.
Example: http://www.deezer.com/en/track/18232696 - tracklist wont show in browser, but downloads perfectly.

**Comment by J05HI** [comment]
Okay great :)

**Comment by J05HI** [comment]
So I can close this?

**Comment by FatKiwi** [comment]
Yes, please do.
