### ISSUE TITLE
[Bug] Artworks for FLAC not embedded

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#12]
Tested with at least 5 tracks. They are stored to tempAlbumCovers, but not embedded to each FLAC file.
No problem for MP3s.

**Comment by J05HI** [comment]
@FatKiwi
Yeah I know this problem :(
I'm currently looking for a way to write Flac tags
Duplicate: [https://github.com/J05HI/DeezLoadr/issues/8](https://github.com/J05HI/DeezLoadr/issues/8)

**Comment by FatKiwi** [comment]
Athame uses TagLib, it's also ported for Node.js https://www.npmjs.com/package/taglib2
Also mini comparsion here: https://blog.kaiserapps.com/node_js_id3_tag_libraries_which_is_the_best/

Hope that helps.

**Comment by J05HI** [comment]
@FatKiwi 
Great!!! Thank you very much!!!

**Comment by J05HI** [comment]
@FatKiwi 
I hope it has all tags we need :)
