### ISSUE TITLE
FILESIZE_* may be a string

### ISSUE THREAD

**Issue by azgul** [J05HI/DeezLoadr#14]
```
  FILESIZE_AAC_64: 0,
  FILESIZE_MP3_64: '1771936',
  FILESIZE_MP3_128: '3543490',
  FILESIZE_MP3_256: 0,
  FILESIZE_MP3_320: '8851456',
  FILESIZE_FLAC: '0',
  FILESIZE: '3543490',
```
The properties in the JSON their API outputs does not have consistent types.

This causes the `0 === trackInfos.FILESIZE_FLAC` check to be invalid because it assumes that `FILESIZE_FLAC` would be an integer, which you can see above it is not

**Comment by J05HI** [comment]
@azgul
Oh thanks :)
What a bad api 🙄
