### ISSUE TITLE
Corrupt files, probably when there is no flac to download

### ISSUE THREAD

**Issue by lasic01** [J05HI/DeezLoadr#18]
As in title. When you try download album, which probably isnt avaible in flac it just download 32kb files, probably covers. There is no error message.

**Comment by azgul** [comment]
due to https://github.com/J05HI/DeezLoadr/issues/14

**Comment by J05HI** [comment]
@azgul
Yeah duplicate :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
