### ISSUE TITLE
Small change and looking for a way for...

### ISSUE THREAD

**Issue by UserForTheOnlyTopic** [J05HI/DeezLoadr#2]
Thanks for the stuff! It's simple and launches faster than the one old. Now i use your app. The small change is it would be good if an option was (a flag if we speak about the console app) or it can always be by default that names of songs were like "01 - <name_of_a_song>" but not only "<artist_name> - <name_of_a_song>".

And now about one moment: some albums/songs aren't available in almost all countries and if you know/find a way to distinguish in which countries they are available and write for them like
"DOWNLOADING... <some_text_like_'ERROR'_or_what_you_want>. Available only in: <a_list_of_countries_where_it's_available>" or something like, it would be great.

For example, the album with unavailable songs for tests:
http://www.deezer.com/album/14520936

**Comment by J05HI** [comment]
@UserForTheOnlyTopic
Hello,

I'll make the download dir and filename configurable in the future.

**Comment by UserForTheOnlyTopic** [comment]
Hi, @J05HI! It's great! I will wait for it with patience. Thank you!
P.S.: also there is one thing that some albums are available in only a couple of countries or even only one, so any tracks of their existing on the site aren't shown, except you know they're on the site and know a country they're available for that after it you can pick the country and find it on the site by searching, but i don't know how to learn about existing such albums when you don't see any sign of their existing. For example, the album for tests:  HOPE by Carpark North that's on the site but i don't know for which countries it's available for (i haven't found a country that makes possible to see the album). If this moment how to learn about hidden albums become clear in future, it will be very good.

**Comment by J05HI** [comment]
@UserForTheOnlyTopic

I'll add search functionality for that in the future

**Comment by UserForTheOnlyTopic** [comment]
@J05HI, great! OK, i took into account that, if i get a thought with something that would be not bad to have, i will write it there. Good plans are listed there, the app works and it's important at that time though, other is secondary.

**Comment by J05HI** [comment]
Great :)

**Comment by J05HI** [comment]
@UserForTheOnlyTopic 

I have tested downloading songs which are not allowed in my country and it works.
What have you done that it doesn't?

**Comment by UserForTheOnlyTopic** [comment]
@J05HI , now those songs are available and it's weird, even the album HOPE by Carpark North became opened, because some time ago they were disabled and the album on deezer was hidden that even Googling didn't help. Although there is another example of an unavailable song:
http://www.deezer.com/track/416516082
Nothing helps. Although the song exists, it's noticeable by size of flac.

**Comment by J05HI** [comment]
@UserForTheOnlyTopic 
And downloading this song doesn't work?

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
