### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by oO-u-Oo** [J05HI/DeezLoadr#23]
Do not bother to solve the tags, the deezer page contains so many mistakes that it is not worth wasting time on it besides the record companies do not even bother to provide certain information about the tracks, I've been able to check in very many albums, so I tell him not to waste time on the tags..

**Comment by J05HI** [comment]
@oO-u-Oo
Okay can you provide an example :)
Maby I'll implement the Discogs api for tagging in the future.

**Comment by tazitus** [comment]
There are many other tools that are really good at tagging. There is no need in my opinion to replicate the effort that has already gone into them. The tags that Deezer provides are good enough for those tools to start working.

**Comment by oO-u-Oo** [comment]
@J05HI 
I have decided to customize and translate the script of stevehero.

**Comment by ThePlayingGoblin** [comment]
To be honest, I think the tagging works just fine. Some tracks don't get tagged at all because they're probably older tracks.

**Comment by oO-u-Oo** [comment]
@ThePlayingGoblin
There are a lot of new albums that the tags are incomplete and with errors, I say you for experience.

**Comment by oO-u-Oo** [comment]
@J05HI 
Maybe this will help you.
https://oauth-api.beatport.com/

**Comment by J05HI** [comment]
I'll take a look at it :)
