### ISSUE TITLE
[Solved] Metadata artwork bug with latest commits [When FLAC is not available]

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#24]
Just built the new sources. 

I get this after each download:

`Downloading "blablabla"[ 'title',
  'artist',
  'album',
  'copyright',
  'performerInfo',
  'trackNumber',
  'partOfSet',
  'ISRC',
  'encodingTechnology',
  'comment',
  'year',
  'image' ]
√ Downloaded "blablabla"`

Now the metadata artwork is no more embedded to mp3s
EDIT: ONLY when FLAC is not available and switches to MP3.
EDIT2: Don't know what happened. Tried few more times and now it works, you can close this. Please take note of the downloading text though. Shows useless info for end-user and might have been the culprit for my first unsuccessful tries.

**Comment by J05HI** [comment]
@FatKiwi
Yeah already removed it but haven't built it, sorry.

**Comment by J05HI** [comment]
@FatKiwi 
Fixed and build in latest commit: [https://github.com/J05HI/DeezLoadr/commit/051049e01e87cc2a4a19002341c1a3168a37d84a](https://github.com/J05HI/DeezLoadr/commit/051049e01e87cc2a4a19002341c1a3168a37d84a)
