### ISSUE TITLE
Path format

### ISSUE THREAD

**Issue by oO-u-Oo** [J05HI/DeezLoadr#25]
This should be the download route.
**DOWNLOADS/[album]/[track_number]. [artist] - [title].mp3/flac**

**Comment by J05HI** [comment]
@oO-u-Oo
Does iTunes do it like that?

**Comment by oO-u-Oo** [comment]
@J05HI 
I do not know how iTunes does it, the route of your application creates too many folders for a single album, the Athame application lets you choose the route, maybe if you decide to do the gui version you could do it if you wish.

**Comment by J05HI** [comment]
@oO-u-Oo
Planned for v1.3.0: [https://github.com/J05HI/DeezLoadr/issues/26](https://github.com/J05HI/DeezLoadr/issues/26)
