### ISSUE TITLE
[Bug] FLAC album downloads corrupted with new build

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#29]
If I try to download a whole album in FLAC, FLAC with proper size downloads, but the header is corrupted and is unplayable.

If I download only the same song from same album and compare it, the only difference is the header.

Instead of starting with `fLaC   "   < @B` it says `ID3    lTIT2" (+songs ID3 tags and especially png image)`.
This makes FLAC album downloads corrupted.  You did something with the FLAC album metadata insertion, but it should be inserted after the header.

No problem for MP3 album downloads.

**Comment by tazitus** [comment]
See https://github.com/J05HI/DeezLoadr/issues/28 and https://github.com/J05HI/DeezLoadr/issues/8

**Comment by FatKiwi** [comment]
I know about it. Maybe he tried to implement it with this build, but it's non-working. Maybe this shouldn't be compiled early if it's buggy.

**Comment by J05HI** [comment]
I'll remove the tagging for flac till now.
Will implement another tagger.

**Comment by J05HI** [comment]
@FatKiwi @tazitus 
Fixed :)
