### ISSUE TITLE
App not reading URLs with /es/

### ISSUE THREAD

**Issue by GerasSB** [J05HI/DeezLoadr#3]
I was trying to download this album:

http://www.deezer.com/es/album/1650665

and for some reason it wasn't working. Then I quickly realized it might be the "/es/" since the website defaults me to Spanish. I removed it and it worked. It's a workaround, but having it work from the get go would be nice.

**Comment by J05HI** [comment]
@GerasSB

Thanks!
Will fix it as soon as possible :)

**Comment by J05HI** [comment]
@GerasSB 

Fixed it in the latest release: [https://github.com/J05HI/DeezLoadr/releases](https://github.com/J05HI/DeezLoadr/releases)
