### ISSUE TITLE
Linked titles don't get downloaded

### ISSUE THREAD

**Issue by throwfil** [J05HI/DeezLoadr#34]
Sometimes there are linked titles in albums, which the loader doesn't download (technically it creates a zero byte file for the track).
e.g. track 4 here:
http://www.deezer.com/de/album/49296292
There is a "show source" button next to the linked track.

**Comment by FatKiwi** [comment]
Interesting. Track 4 doesn't work with the webscript too - empty 0kb files.

**Comment by J05HI** [comment]
Okay thank you very much :)
I think it's because I'm parsing the deezer page to get the track infos

**Comment by J05HI** [comment]
Will take a look at the Sparx source too :)

**Comment by J05HI** [comment]
Should be fixed now with [https://github.com/J05HI/DeezLoadr/commit/d1eb9205a3e4c12d02e04b310a190ddcda486d16](https://github.com/J05HI/DeezLoadr/commit/d1eb9205a3e4c12d02e04b310a190ddcda486d16)
Please give feedback :)

**Comment by FatKiwi** [comment]
Still downloads 0kb files 😥 
http://www.deezer.com/de/track/413733032

**Comment by tazitus** [comment]
It seems like that exact track is simply not available on Deezer. Deezloader gets around this by downloading the alternative provided by the api.deezer.com/track API.
In this case it links to a remastered version on a Sinatra album.

**Comment by FatKiwi** [comment]
I agree, it is partially unavailable. But Sparx's downloader can download it properly with gw-light API.

**Comment by J05HI** [comment]
@FatKiwi
Strange. I'm using a similar logic like it.

**Comment by tazitus** [comment]
@FatKiwi 
Are you sure it doesn't just download the alternative/fallback ?

**Comment by FatKiwi** [comment]
Track hash from cdn-proxy his downloader pulls: 2edb25cf8a1029e221540194b902c3f0dae606499b230bf6b12dcc12716767d7d88b1ff75fdb616fedf3bd0f4aedb5012fa828b1adace96dc2fc300607389ea752389e9098899ee25d9867fa187c85543d0d871c865d5449ab015558f784802f

Worked 2 days ago, maybe Deezer is watching. 
Now it says 403 Forbidden.

**Comment by FatKiwi** [comment]
OK, his downloader works ONLY if you put the whole album and select track.
Hash then is: d16d72c933f0f835fdd40386ce7d1aa3f15b8710bbd12616c44cbfdd2b91b76f4a02a3c059700c1420bc729de90e2e95999d0ea799a4cb8a6e037ff6143e7b5691283f78d1ae68e262ef6da5be484dc43d0d871c865d5449ab015558f784802f

According to Tidal, tracks 4 & 16 are unavailable. Track 16 plays in Deezer however, but cannot be downloaded directly by Sparx's downloader and yours too.
Webscript works for Track16.

**Comment by FatKiwi** [comment]
Track hash his downloader pulls:
56d1d6a8407046c02ad18a7201711c7903f9e72cc2d1d27a70ff1f5ca5f78df82d1bca411d634b00bd8df785d944abf62b91526e999f5f82ac52bcc9f0092e5353ff3c4e4e46ae739384ff10e8aeb3df

**Comment by J05HI** [comment]
@FatKiwi @throwfil @tazitus 

Should be fixed now, it downloads alternatives in the latest build :)
Please report back.

**Comment by FatKiwi** [comment]
Nice job. :)
