### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by zkan1974** [J05HI/DeezLoadr#36]
please change the theme please not nice interface

**Comment by FatKiwi** [comment]
The interface is console style. I like it.

**Comment by zkan1974** [comment]
Okay, thanks, you're the producer of this program :)

**Comment by FatKiwi** [comment]
Not only you're disrespectful (and ungrateful), but sarcastic too.

**Comment by J05HI** [comment]
@zkan1974
Sorry I can't work on things really often :(
GUI will come sometime (if console is stable) .

**Comment by J05HI** [comment]
Will close it now because it's currently not in the near scope.
