### ISSUE TITLE
 real studio music

### ISSUE THREAD

**Issue by zkan1974** [J05HI/DeezLoadr#37]
Is music real flac music

**Comment by FatKiwi** [comment]
90% of the times yes. Some labels upload fake flac in rare cases.

**Comment by zkan1974** [comment]
will you solve this problem

**Comment by jonaaa20** [comment]
Of course they are. Use auCDtect task manager to confirm it.

**Comment by J05HI** [comment]
@zkan1974
How should I solve this?
If deezer doesn't offer a better quality I can't do anything :(

**Comment by ThePlayingGoblin** [comment]
Studio quality is not possible on deezer. Best quality out there is cd quality (16-bit). They also just partnered with mqa, which is worse than 16-bit quality.

**Comment by J05HI** [comment]
You're right @ThePlayingGoblin 
@zkan1974 For more infos see [https://support.deezer.com/hc/de/articles/115004589249-Deezer-HiFi-FAQ](https://support.deezer.com/hc/de/articles/115004589249-Deezer-HiFi-FAQ)

**Comment by FatKiwi** [comment]
@ThePlayingGoblin why do you say MQA is worse?

**Comment by tazitus** [comment]
Probably because it uses lossy compression

**Comment by jonaaa20** [comment]
MQA is just marketing.

**Comment by ThePlayingGoblin** [comment]
@FatKiwi, MQA confirms that their codec is "better than CD quality" which is complete bs. Because MQA is lossy, that means bit and pieces of the original work have been removed. Its indestinguishable to the human ear, but when it comes to your music library, you're better off with 16-bit lossless.

**Comment by FatKiwi** [comment]
They still use FLAC and the lossy part is the frequencies over 20khz. But it's not completely lossy and theoretically should be better than 44khz. I have downloaded and compared MQA vs 16-bit and MQA is 16-bit + better sampling rate and extra information (looks so on spectrogram).

**Comment by oO-u-Oo** [comment]
that is, tidal and deezer are a real scam according to audio checkers program

**Comment by jonaaa20** [comment]
@oO-u-Oo use auCDtect and you'll see that Deezer/Tidal isn't a real scam, like @FatKiwi said, 90% are real flacs, there's some upscaled FLACs but most of them are real ones.

**Comment by oO-u-Oo** [comment]
@jonaaa20 
i have been able to verify that in a lot of tracks it says "MPEG 95%" and not CDDA more than 90%, knows some program that checks the 24bits of tidal?

**Comment by jonaaa20** [comment]
90%? Interesting. About tidal, probably their 24-bit are just lossy, nothing impressive.

**Comment by oO-u-Oo** [comment]
When ones big companies such as tidal and deezer announced bass drum and saucer their damn flac and you realize that it is not true is a scam if even if it's just one track.

**Comment by jonaaa20** [comment]
And that's why i don't care about FLACs, all my songs are MP3 320kbps, i'm fine with it.

**Comment by FatKiwi** [comment]
@oO-u-Oo depends on the label if they're strict (most of them are). However, I know a specific artist who always converts his MP3 to fake WAV and sends to label. His tracks are always fake FLAC.
24bit flac can be verified with [fbits.cmd](https://hydrogenaud.io/index.php?action=dlattach;topic=97746.0;attach=7493) script. You can check [this](https://hydrogenaud.io/index.php/topic,97746.0.html)

**Comment by J05HI** [comment]
@FatKiwi
Yeah but you can't check this on the streaming site so he thinks no one will get that :D

**Comment by FatKiwi** [comment]
Oh...  🤣

**Comment by J05HI** [comment]
@FatKiwi
But you could really write to deezer.
They should check their FLACs before uploading.

**Comment by FatKiwi** [comment]
Unfortunately they don't care. 😞  Deezer is just a platform and they will not spend resources on checking 41+ million tracks. This is the job of the labels {and again most of them don't care) as long as final file they get is WAV.

**Comment by jonaaa20** [comment]
I agree with @FatKiwi, they don't care about it, same as tidal, i was downloading some FLACs from tidal to convert it to AAC, i saw some "MP3-like" quality on their FLACs, and that's why i don't pay for these "hifi streaming services" :grin:

**Comment by oO-u-Oo** [comment]
@FatKiwi 
Script fbits.cmd don't work in windows,

**Comment by J05HI** [comment]
Found a nice tool to check FLAC quality :)
[http://losslessaudiochecker.com/](http://losslessaudiochecker.com/)

**Comment by oO-u-Oo** [comment]
@J05HI 
I have tried that tool but it does not convince me, the program that jonaaa20 has said is the one that convinces me but does not work with 24bits.

**Comment by J05HI** [comment]
@oO-u-Oo 
Which tool? For Windows?

**Comment by oO-u-Oo** [comment]
This program does not work with the 24bits flac.
http://y-soft.org/English/products/auCDtect-Task-Manager/

I have tried this too but it does not work with the 24bits flac.
http://www.freewarefiles.com/Audiochecker-Beta_program_21299.html

**Comment by FatKiwi** [comment]
@oO-u-Oo you need to have flac.exe in the same folder or environmental path. Script works if you drag & drop files on it.

**Comment by oO-u-Oo** [comment]
@FatKiwi
Post the flac.exe program direct link please.

**Comment by FatKiwi** [comment]
Google is your friend. [This time only](https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.2-win.zip)

**Comment by oO-u-Oo** [comment]
@FatKiwi 
Thanks very much !

**Comment by oO-u-Oo** [comment]
I can verify through the tests that I have done that the fbits.cmd script is a good audio analyzer, with this script and the program auCDtect-Task-Manager i can know the "supposed artist" bastard.

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
