### ISSUE TITLE
Auto close when it finishes downloading in FLAC

### ISSUE THREAD

**Issue by MalexTP** [J05HI/DeezLoadr#40]
I use Linux, idk why it happen. DeezLoadr 1.2
[Gif](https://gfycat.com/gifs/detail/CavernousLeafyArcticwolf)

**Comment by FatKiwi** [comment]
#31 is now fixed. You use old build from release page. Try these instead: https://github.com/J05HI/DeezLoadr/tree/master/BUILDS

**Comment by MalexTP** [comment]
Works fine but rare bug:

♫ Select music quality: FLAC - 1411 kbps


♫ Deezer URL: https://www.deezer.com/es/track/396540422

{ id: 46578412,
  title: 'Take Off',
  upc: '840094236790',
  link: 'https://www.deezer.com/album/46578412',
  share: 'http://www.deezer.com/album/46578412?utm_source=deezer&utm_content=album-46578412&utm_term=0_1511843474&utm_medium=web',
  cover: 'https://api.deezer.com/album/46578412/image',
  cover_small: 'https://cdns-images.dzcdn.net/images/cover/9bf7deb8764db40b0e7e59841514e67e/56x56-000000-80-0-0.jpg',
  cover_medium: 'https://cdns-images.dzcdn.net/images/cover/9bf7deb8764db40b0e7e59841514e67e/250x250-000000-80-0-0.jpg',
  cover_big: 'https://cdns-images.dzcdn.net/images/cover/9bf7deb8764db40b0e7e59841514e67e/500x500-000000-80-0-0.jpg',
  cover_xl: 'https://cdns-images.dzcdn.net/images/cover/9bf7deb8764db40b0e7e59841514e67e/1000x1000-000000-80-0-0.jpg',
  genre_id: 106,
  genres: { data: [ [Object], [Object] ] },
  label: '692152 Records DK',
  nb_tracks: 7,
  duration: 1428,
  fans: 6,
  rating: 0,
  release_date: '2017-08-19',
  record_type: 'album',
  available: true,
  tracklist: 'https://api.deezer.com/album/46578412/tracks',
  explicit_lyrics: false,
  contributors: 
   [ { id: 9786094,
       name: 'Donald Bucks',
       link: 'https://www.deezer.com/artist/9786094',
       share: 'http://www.deezer.com/artist/9786094?utm_source=deezer&utm_content=artist-9786094&utm_term=0_1511843474&utm_medium=web',
       picture: 'https://api.deezer.com/artist/9786094/image',
       picture_small: 'https://cdns-images.dzcdn.net/images/artist//56x56-000000-80-0-0.jpg',
       picture_medium: 'https://cdns-images.dzcdn.net/images/artist//250x250-000000-80-0-0.jpg',
       picture_big: 'https://cdns-images.dzcdn.net/images/artist//500x500-000000-80-0-0.jpg',
       picture_xl: 'https://cdns-images.dzcdn.net/images/artist//1000x1000-000000-80-0-0.jpg',
       radio: true,
       tracklist: 'https://api.deezer.com/artist/9786094/top?limit=50',
       type: 'artist',
       role: 'Main' } ],
  artist: 
   { id: 9786094,
     name: 'Donald Bucks',
     picture: 'https://api.deezer.com/artist/9786094/image',
     picture_small: 'https://cdns-images.dzcdn.net/images/artist//56x56-000000-80-0-0.jpg',
     picture_medium: 'https://cdns-images.dzcdn.net/images/artist//250x250-000000-80-0-0.jpg',
     picture_big: 'https://cdns-images.dzcdn.net/images/artist//500x500-000000-80-0-0.jpg',
     picture_xl: 'https://cdns-images.dzcdn.net/images/artist//1000x1000-000000-80-0-0.jpg',
     tracklist: 'https://api.deezer.com/artist/9786094/top?limit=50',
     type: 'artist' },
  type: 'album',
  tracks: 
   { data: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] } }
✔ Downloaded "Donald Bucks - Earthquake"


♫ Deezer URL:

**Comment by FatKiwi** [comment]
@MalexTP, that's another issue. Looks same as #24, but that was fixed.
I tried downloading it, both MP3 and FLAC versions - downloads normal without this text.

**Comment by FatKiwi** [comment]
I can confirm this shows on latest build.

Worked fine before this **a20f553**

**Comment by J05HI** [comment]
Yeah, sorry :(
Will remove the console.log 🙄

**Comment by FatKiwi** [comment]
Hoping "Cannot read property 'name' of undefined" for specific tracks won't be back again.

**Comment by J05HI** [comment]
@MalexTP @FatKiwi 
Removed it in [https://github.com/J05HI/DeezLoadr/commit/a20f5539033785e1dd4dc714e7cc3077e08863bd](https://github.com/J05HI/DeezLoadr/commit/a20f5539033785e1dd4dc714e7cc3077e08863bd) :)
