### ISSUE TITLE
Needs a GUI

### ISSUE THREAD

**Issue by jackpot08** [J05HI/DeezLoadr#43]
great tool, but needs a GUI similar to deezloader.

**Comment by tazitus** [comment]
https://github.com/J05HI/DeezLoadr/issues/36

**Comment by J05HI** [comment]
Some day it will come :)
Till now you have to be satisfied with the console.

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
