### ISSUE TITLE
Probably patched it

### ISSUE THREAD

**Issue by Sugardemon** [J05HI/DeezLoadr#45]
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× StatusCodeError: 408 - "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× TypeError: Cannot read property 'name' of undefined
× RequestError: Error: socket hang up
× RequestError: Error: socket hang up
× RequestError: Error: socket hang up
× RequestError: Error: socket hang up
× RequestError: Error: socket hang up
× RequestError: Error: socket hang up
× RequestError: Error: socket hang up
× RequestError: Error: socket hang up
× StatusCodeError: 408 - "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"
× RequestError: Error: connect ETIMEDOUT 185.60.92.33:80

**Comment by J05HI** [comment]
@Sugardemon

Could you please provide more infos.
What you did, which song/album/playlist, which OS,...

**Comment by J05HI** [comment]
@Sugardemon 

Should be fixed now :)
Please report back.

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
