### ISSUE TITLE
Flac metadata addition

### ISSUE THREAD

**Issue by Tormiasz** [J05HI/DeezLoadr#46]
Could this be implemented for flac files? https://github.com/claus/flac-metadata

**Comment by J05HI** [comment]
Duplicate: [https://github.com/J05HI/DeezLoadr/issues/8](https://github.com/J05HI/DeezLoadr/issues/8)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
