### ISSUE TITLE
Having problem downloading albums greater then 10 tracks.

### ISSUE THREAD

**Issue by lonelysomale** [J05HI/DeezLoadr#47]
So i have been having this issue with downloading albums. If i download an album with more then 10 tracks, the rest of the tracks are downloaded around half way. Here is an example of a 12 track compilation i was trying to archive https://i.imgur.com/f6cdgjf.jpg. I am using Windows 7 x64 bit if that is relevant. 

Thank you

**Comment by J05HI** [comment]
Duplicate and already fixed but haven't compiled it yet: [https://github.com/J05HI/DeezLoadr/issues/44](https://github.com/J05HI/DeezLoadr/issues/44)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
