### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by oO-u-Oo** [J05HI/DeezLoadr#49]
When album has been downloaded, it does not let the quality be selected for next album, the application must be closed in order to download it,

**Comment by J05HI** [comment]
Should I really add this for every download?

**Comment by oO-u-Oo** [comment]
I think so, because there are a lot of albums that are not in flac, it would be annoying to have to close the application when an album is not in flac, if for example an album is not in flac would be good to show a warning "Only in mp3" and then leave select any quality in mp3 without having to close the application every two x three, what do you think of the idea?

**Comment by J05HI** [comment]
Okay I'll look a the album is not in flac message, should be already there.

**Comment by oO-u-Oo** [comment]
Thanks very much !, You are a big person, if you do not get to tell me in this message I would not have aware the new improvements in 1.2.0., its application is wonderful, it does exactly the same as the plugins tidal and deezer for athame when it is not available in flac and master (24bits) an album, I loved that it does it automatically without the need to choose the quality.

Greetings.

**Comment by MalexTP** [comment]
app can download max quality automatically? I think

**Comment by jonaaa20** [comment]
Yes @MalexTP.

**Comment by J05HI** [comment]
Yeah

**Comment by oO-u-Oo** [comment]
@J05HI 
This topic is also solved, you can close this topic.

**Comment by J05HI** [comment]
@oO-u-Oo
Thanks!

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
