### ISSUE TITLE
Flac

### ISSUE THREAD

**Issue by oO-u-Oo** [J05HI/DeezLoadr#50]
It is possible when an album is not available in flac that shows a warning "Only available in mp3"?, little files are downloaded when it is not available.

**Comment by J05HI** [comment]
It already should do this

**Comment by oO-u-Oo** [comment]
Thanks for solving it, you can close this topic please.

**Comment by lasic01** [comment]
It shows that message but then there is this bug:

♫ Deezer URL: (node:22664) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by J05HI** [comment]
@lasic01
Already fixed :)
But haven't compiled it yet 😅

**Comment by J05HI** [comment]
@oO-u-Oo 
Could you please provide a track which isn't available in FLAC :)

**Comment by J05HI** [comment]
@oO-u-Oo 
Could you please provide a track which isn't available in FLAC :)

**Comment by oO-u-Oo** [comment]
This topic is solved, files are not longer downloaded when it is not in flac

http://www.deezer.com/track/10509078

**Comment by J05HI** [comment]
@oO-u-Oo
Okay great! ☺

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
