### ISSUE TITLE
Artist in filename

### ISSUE THREAD

**Issue by SchwanzusLongus** [J05HI/DeezLoadr#57]
Hi J05HI,
as first, you've done a great work so far.
Hope you can handle flac tagging soon.
Until it works, it would be great, artist is included in filename, i.e. "Artist - Title.flac".
With this naming, I could tag it with various tools, by reading out filename to tag.

THX

**Comment by oO-u-Oo** [comment]
Read this topic. ;)
https://github.com/J05HI/DeezLoadr/issues/25

**Comment by J05HI** [comment]
@SchwanzusLongus
First of all thank you very much for your donation!!! 

Filename configuration will be added soon like @oO-u-Oo already mentioned. 

There is already a pull request for flac tagging open: [https://github.com/J05HI/DeezLoadr/pull/58](https://github.com/J05HI/DeezLoadr/pull/58)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
