### ISSUE TITLE
Remove builds from repository

### ISSUE THREAD

**Issue by rafaeldamasceno** [J05HI/DeezLoadr#59]
It massively increases clone time, which downloads a ton of builds that probably aren't even the target that we want. Git is not meant to share binaries, just source code.

Builds should be kept at the Downloads section of every release.

In fact, as it is so easy to build it on your own, it's probably even better to not even ship builds.

**Comment by J05HI** [comment]
@rafaeldamasceno
Okay I'll do that :)

**Comment by J05HI** [comment]
@rafaeldamasceno 
Will do this with the release of v1.2.1

**Comment by tabepic** [comment]
@J05HI Are you planning on removing binaries entirely, or just moving them to the downloads area?

Personally I think it's best to just distribute the source, and then improve the build scripts to be more robust and featureful. This way, mildly technical people can easily install it, and we don't run the risks of hosting binaries that run "out-of-the-box".

**Comment by J05HI** [comment]
I'll host them somewhere else

**Comment by tabepic** [comment]
Ok, sounds like a good idea.

**Comment by throwfil** [comment]
The build folder is back since one of the last commits.

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
