### ISSUE TITLE
Download links broken (Front Page only)

### ISSUE THREAD

**Issue by ThePlayingGoblin** [J05HI/DeezLoadr#6]
I get error 404 when trying to download Deezloadr.

**Comment by ThePlayingGoblin** [comment]
Nvm, I didn't look well.

**Comment by ThePlayingGoblin** [comment]
Edit: The links on the front page are broken, but work when you go to the 1.2.0 builds section.

**Comment by jonaaa20** [comment]
Working fine here? Why have you opened a issue?

**Comment by ThePlayingGoblin** [comment]
This:
![404](https://user-images.githubusercontent.com/32787189/33227203-b79561b2-d152-11e7-8304-c9ee731e1611.jpg)

**Comment by jonaaa20** [comment]
Fine here. I still don't see a reason to open a issue, btw, seems that you're the only one having this problem...

**Comment by J05HI** [comment]
@ThePlayingGoblin @jonaaa20
Yeah the links in the Readme are broken.
Sorry I've forgotten to change them

**Comment by J05HI** [comment]
Fixed it :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
