### ISSUE TITLE
Multiple download

### ISSUE THREAD

**Issue by troufiniou** [J05HI/DeezLoadr#60]
Can be nice to purpose multiple link.

At the launch of the soft ask how many link we want and purpose oone by one the link.

**Comment by J05HI** [comment]
Duplicate: [https://github.com/J05HI/DeezLoadr/issues/5](https://github.com/J05HI/DeezLoadr/issues/5)

How should I add this to a console app?
Maby wait for the GUI :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
