### ISSUE TITLE
[BUG] Duplicate Flac Metadata Tags

### ISSUE THREAD

**Issue by RandomNinjaAtk** [J05HI/DeezLoadr#61]
So I just tested the new build and it works, but when looking at the tags in MP3TAG it seems to written all tags twice, heres an example:

![capture](https://user-images.githubusercontent.com/8386416/33573670-86ca205e-d904-11e7-9826-deafaff9ec0f.PNG)

**Comment by J05HI** [comment]
@RandomNinjaAtk 
Okay you opend a new issue :)

**Comment by J05HI** [comment]
@RandomNinjaAtk 

Asked the author of the lib here: [https://github.com/claus/flac-metadata/issues/4](https://github.com/claus/flac-metadata/issues/4)
Maybe I get an answer soon :)

**Comment by RandomNinjaAtk** [comment]
Also after attempting to fix tags using Mp3Tag doesn't seem to work, it's like impossible to remove/delete the duplicates.

**Comment by RandomNinjaAtk** [comment]
@J05HI 
Somehow I doubt you'll get an answer based on an open pull request with no response, but makes me wonder if the outstanding pull request resolves it.... see here: 
https://github.com/A----/flac-metadata/tree/concurrency-issue

**Comment by J05HI** [comment]
@RandomNinjaAtk

Yeah but I think this is for tagging multiple files at the same time.

**Comment by J05HI** [comment]
Let's see...
Maybe I'll fork it and fix it. Looks like the author isn't working anymore :(

**Comment by J05HI** [comment]
@RandomNinjaAtk 
Yeaaah! Got it to work :)
Will commit it after cleanup.

**Comment by FatKiwi** [comment]
Downloaded song in question. No problem here.
![snap2](https://user-images.githubusercontent.com/9163913/33624866-9dcd0d2c-d9ed-11e7-9bba-128deabb86c2.png)

**Comment by J05HI** [comment]
@RandomNinjaAtk 

Should be fixed now :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
