### ISSUE TITLE
Don't tag fine the cover on FLAC and MP3

### ISSUE THREAD

**Issue by MalexTP** [J05HI/DeezLoadr#63]
Audacious player, read all tags but not are reading cover of that id3 and flac-metadata

![image](https://user-images.githubusercontent.com/24663715/33601917-bb80f09e-d97b-11e7-820b-bd428e42a2fe.png)
![image](https://user-images.githubusercontent.com/24663715/33601960-e117c224-d97b-11e7-8faf-03241e22d2bb.png)

But it read all tags normally, but not of Deezloadr :c
![image](https://user-images.githubusercontent.com/24663715/33602090-44c4bc96-d97c-11e7-917b-aa6bb5243645.png)
![image](https://user-images.githubusercontent.com/24663715/33602254-bc564ec8-d97c-11e7-81fe-0fdc6051607f.png)

**Comment by FatKiwi** [comment]
For FLAC there is no cover yet. But MP3 looks good. Just downloaded song in question, Audacious 3.9 Windows and it works perfect.
Update your player and download last build from repo.
![snap1](https://user-images.githubusercontent.com/9163913/33624587-c529cec4-d9ec-11e7-9505-62c958d5c1be.png)

**Comment by J05HI** [comment]
@MalexTP 
Have you built it on your own?
Because I haven't built it yet.

**Comment by FatKiwi** [comment]
Yes, just build last source from here. Tried with last published build too - no such problem for me.

**Comment by J05HI** [comment]
@MalexTP 
Which song did you downloaded?
Can you provide an URL?

**Comment by RandomNinjaAtk** [comment]
@J05HI Working for me without issues

**Comment by J05HI** [comment]
@RandomNinjaAtk 
For me too.
Really strange :(

**Comment by MalexTP** [comment]
Probably is only a problem of Linux?

**Comment by MalexTP** [comment]
And yes, i downloaded ultimate sources and tested

**Comment by J05HI** [comment]
@MalexTP 
Sorry I currently can't test it with linux :(

**Comment by MalexTP** [comment]
![image](https://user-images.githubusercontent.com/24663715/33628915-4585d85a-d9d0-11e7-870d-abc0f6742f1f.png)
![image](https://user-images.githubusercontent.com/24663715/33628939-56fa429c-d9d0-11e7-9adf-9ff0c9593e93.png)
![image](https://user-images.githubusercontent.com/24663715/33628982-7e5d88d0-d9d0-11e7-82e2-0e900dd96bac.png)
It tag cover, but some programs don't are reading the tag

**Comment by J05HI** [comment]
@MalexTP 
Shit strange :(
I tried it with VLC, Groove Music, Windows Media Player and ITunes. All reading the tags and cover fine.

**Comment by FatKiwi** [comment]
So that's Audacious for Linux bug then. Seems to be showing properly in the last one.

**Comment by J05HI** [comment]
@MalexTP 
Could you try it with VLC on Linux?

**Comment by MalexTP** [comment]
@J05HI last photo is from vlc

**Comment by MalexTP** [comment]
ill try to download the song of yesterday and see

**Comment by J05HI** [comment]
@MalexTP 
Okay

**Comment by MalexTP** [comment]
i have maked a modification for Deezloader and abled FLAC download, idk if you want see that

**Comment by MalexTP** [comment]
![image](https://user-images.githubusercontent.com/24663715/33629370-ca5a15ea-d9d1-11e7-956d-01cdaf319ffd.png)

![image](https://user-images.githubusercontent.com/24663715/33629353-c00f6748-d9d1-11e7-9aaa-6937c33ec870.png)

It don't download cover for that song :c

**Comment by J05HI** [comment]
@MalexTP 
Submit a pull request :)

**Comment by J05HI** [comment]
@MalexTP 
Is the cover in the "tempAlbumCovers" folder?

**Comment by MalexTP** [comment]
yes, rare

**Comment by J05HI** [comment]
@MalexTP 
Strange
And it doesn't show an error?

**Comment by MalexTP** [comment]
♫ Deezer URL: http://www.deezer.com/es/track/409007492

✔ Downloaded "Spag Heddy - Bring It Ft. Virus Syndicate (Lifecycle Remix)"


♫ Deezer URL:

**Comment by MalexTP** [comment]
And probably you can make something what it delete pre taggged and tag again? Duplicates
![image](https://user-images.githubusercontent.com/24663715/33630122-3bfe0b28-d9d4-11e7-9690-1068aaca4d86.png)

**Comment by MalexTP** [comment]
Ok, I'll try it

**Comment by MalexTP** [comment]
Now on the last build don't want tag songs, only cover

**Comment by J05HI** [comment]
Fixed with: [https://github.com/J05HI/DeezLoadr/commit/ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6](https://github.com/J05HI/DeezLoadr/commit/ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6)

I need someone who can add the flac and metaflac binaries for OSX and Linux.

**Comment by J05HI** [comment]
Build and try it now :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
