### ISSUE TITLE
FLAC not tagged, app crashes

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#64]
![snap3](https://user-images.githubusercontent.com/9163913/33625681-4514cc8a-d9f0-11e7-8ecb-0cbd13a7e7e4.png)
So I'm trying to download FLAC with latest commits (https://github.com/J05HI/DeezLoadr/commit/39ed13d636242c5fb8e82bd34748321bcead2361) build and the app crashes, FLAC is downloaded, but .flac.temp file 0kb is left too and all the metadata is missing.

Not sure if FLAC meta is ready yet, but according to this (https://github.com/J05HI/DeezLoadr/commit/f33659c87a1e6e7bd9acdac75fff88eebb55607b) and the screenshots - looks so.

**Comment by J05HI** [comment]
@FatKiwi 
Really strange :(
Will take a look at it if tagging is fixed.

**Comment by RandomNinjaAtk** [comment]
When you downloaded the repo, did you make sure that you install all dependencies? Also the latest updates to flac metadata have not been pushed to the branch yet. I'd wait for @J05HI to update this branch with his fixes for the flac metadata and then try again.

**Comment by J05HI** [comment]
@RandomNinjaAtk @FatKiwi 
Yeah that could be a problem (run npm install).
But I think it's really a bug...

**Comment by J05HI** [comment]
@FatKiwi 
Can't replicate this bug :(

**Comment by FatKiwi** [comment]
Close this, works with unmodified script.
I made modifications to the script by removing comment. Seems like it's required now in flac meta.

**Comment by J05HI** [comment]
Oh okay great :)
I'll add options which tags to write in the GUI: [https://github.com/J05HI/DeezLoadr/issues/65](https://github.com/J05HI/DeezLoadr/issues/65)

**Comment by FatKiwi** [comment]
Hope you don't feel disrespected. I share and support your work (btw, check your donations), but if I don't compile it without them removed, it takes a lot of time to retag whole collections for later use. Cheers! 🥇

**Comment by J05HI** [comment]
@FatKiwi 
Thank you very much for your donation!!!

**Comment by FatKiwi** [comment]
Oh, I thought the whole point is promotion for the project (which is bad in some ways, as previous DeezLoader was banned from github :/ )

**Comment by J05HI** [comment]
@FatKiwi 
Yeah I already thought of that but don't know what to do.
Maybe host it somewhere else...
Do you have an idea?

**Comment by FatKiwi** [comment]
Avoid gitlab and private repos, as they can take them down too.
Just keep offline copy and contacts, users can always resurrect it if something bad happens :)

**Comment by J05HI** [comment]
@FatKiwi 
Yeah but where should I host it then?
Need a place where I can put the code to

**Comment by FatKiwi** [comment]
It's fine here for now. Let's think it when it happens. Have no ideas at the moment

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
