### ISSUE TITLE
Question: Can you remove flacVendor tag?

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#66]
Can you remove "let flacVendor = 'DeezLoadr'; as this prevents players to show the FLAC version used?

For example I have the habit of updating flac files with newer encoder version, but this prevents me from seeing the real version of FLAC used.

**Comment by J05HI** [comment]
@FatKiwi
Oh okay. Didn't know that.
Maybe I can remove it but don't know if it works if i don't specify the vendor.
Will try it :)

**Comment by FatKiwi** [comment]
When I remove it, app crashes and no tags written. :/

**Comment by J05HI** [comment]
@FatKiwi
Shit, let's see what I can do...

**Comment by RandomNinjaAtk** [comment]
@J05HI @FatKiwi 

Could go with the "reference libFLAC 1.2.1 20070917" which is the suggested usage from: https://github.com/claus/flac-metadata

**Comment by FatKiwi** [comment]
Yeah but that will fake it once again with a string.
Some flacs from Deezer are using even FLAC 1.1.4 (which is very outdated). Would be nice to know the real version.

Hope you can find a way to skip the vendor tag.

**Comment by J05HI** [comment]
@FatKiwi @RandomNinjaAtk 
Yeah skip or read it first and write it then.

**Comment by J05HI** [comment]
Removed with: [https://github.com/J05HI/DeezLoadr/commit/ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6](https://github.com/J05HI/DeezLoadr/commit/ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6)

I need someone who can add the flac and metaflac binaries for OSX and Linux.

**Comment by tabepic** [comment]
I should be able to do that.
But do you really want to ship binaries with it? Shouldn't it use one installed in the system path?

**Comment by tabepic** [comment]
Also I believe they would be only compatable with a specific version of glibc (statically linking glibc isn't really possible).
Not to mention they would need to be statically linked to work, because otherwise flac looks for a library in /lib/.

**Comment by FatKiwi** [comment]
> Wouldn't it be better to simply require it to be installed (at least on Linux), and just use the system installed binary?

FLAC devs say it should come shipped with most distros. No reason for Linux binaries.
Others here: https://www.videohelp.com/software/FLAC-Encoder

But we need to fix the build bug first. Binaries don't get compiled. 
Maybe PKG doesn't support it yet. https://github.com/zeit/pkg/issues/240

**Comment by tabepic** [comment]
@FatKiwi says it better than I
Just please make sure you include a check to fail gracefully in case flac+metaflac aren't installed.

(In case you still want some x86_64 linux binaries, I put a couple [here](https://ptpb.pw/gtWd.zip))

**Comment by J05HI** [comment]
Let's see... 
Maybe I should use another packager.

**Comment by J05HI** [comment]
@tabepic 
Do you have some binaries for 32bit too?

**Comment by J05HI** [comment]
Build and try it now :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
