### ISSUE TITLE
[IMPORTANT] IF DEEZER TAKES IT DOWN...

### ISSUE THREAD

**Issue by J05HI** [J05HI/DeezLoadr#67]
Hello community,

I started this as a little project and didn't thought that it will get that much attention.

Now I would like to ask you what to do if Deezer takes it down.
Maybe I should host it somewhere else?

Hope you can understand and help me :)

Thank you very much for the support!!!

---

@george B. @MonkeyWrench123 @Matthew D @Hemps37 @scr1ptkiddie @MalexTP @taogre @lostfilm @elguaxo @Karwan1988 @Manghao @izzobot @Jose Suarez @Chehan Ratnasiri @Ralph Slooten @Lachlan @ልዪፕዐ @Aayush Jain @Hussein Ait-Lahcen @Adil Yarulin @Jay Zuo @MarcRdC @John Kearney @Michael Carleton @Nikola Gjorgievski @Cary W. @fabriccioguzman @STX @Cédric Laubacher @bamtan @Damianonymous @CEOYap @Santeri Elo @Ishan 火 Arya @zouhair @HollowsxD @James @GitTheGreek @noisawe @Pratik Bhusal @steph9009 @v9999 @FatKiwi @SDMU @Alp @phend @Aditya Dutt @RandomNinjaAtk @Joshua Soong @desimaniac @KassaliHamza @dragnu5 @therohanchawla @tocy777 @Jonathan Tavares

**Comment by J05HI** [comment]
@FatKiwi 
Yeah :(

My idea would be keep the readme and issues here and add a link to the repo and the builds.
They will be on a filehosting somewhere.
But don't know if they take it down too.

**Comment by bascurtiz** [comment]
If they get after you, they'll threat with legal actions.
''If you don't obey to our wishes, then we'll make it a case with lawyers (for copyright infringement, etc.)''
Then kindly ask u to remove your files where u upped them.

As shown with Deezloader, this worked to make them stop.
But then again, it didn't.
Since you can get the repo thru torrents, mega-links, even mirror of the offical creator here: https://git.2li.ch/various/Deezloader-app/releases

I was one of the guys, who made simple how-to youtube vids to install and use the program.
Although, I had hidden these vids, This way you get way too much popularity, since ppl could share the link or post it on their website.
I suggest u make a new topic, where u ask not to make/share any youtube video's on your program, so it keeps more hidden from the mass (and will be win/win so it stays alive longer).

Be aware, when Deezloader staff decided to go private, so u could only get in, after asking thru pm, they decided u could or not.
This made esp. one guy angry alias 'misfit' (who prolly got denied to enter) and told the group he would inform Deezer. And so it happened...

**Comment by taogre** [comment]
Do it via torrent. That way they cant realy take it down.

taogre

**Comment by RandomNinjaAtk** [comment]
Usenet is also a good option

**Comment by J05HI** [comment]
@bascurtiz
Thanks for the info!
So I can't really do anything.
Only waiting for the mail...

**Comment by J05HI** [comment]
@taogre
Yeah but who seeds it?
Not me with my IP.
And we are to less people...

**Comment by J05HI** [comment]
@RandomNinjaAt
Yeah spread it around if it is time...

**Comment by RandomNinjaAtk** [comment]
@J05HI  One way to draw less attention, would be to never upload compiled builds, that means it would take someone with a bit of know how to build the application themselves.... It's not terribly difficult to build the app. But non tech-savy people will probably not be inclined to go through the trouble. As of right now for me personally the only feature its really missing is full artist support....

**Comment by J05HI** [comment]
@RandomNinjaAtk
Yeah but I would like to serve the app for non techies too

**Comment by FatKiwi** [comment]
> I suggest u make a new topic, where u ask not to make/share any youtube video's on your program, so it keeps more hidden from the mass (and will be win/win so it stays alive longer).

If that's the case, he should probably remove the links and app name from downloaded files too, since people share a lot.

**Comment by RandomNinjaAtk** [comment]
@FatKiwi 

I agree that probably not calling it something directly tied to service it's using would be a better way to obfuscate it...

**Comment by J05HI** [comment]
Yeah without a name it would be better.
But how should I name the repo then :D

**Comment by bascurtiz** [comment]
Suggestion: J05HI.exe =)

**Comment by DesmondSky** [comment]
Found this app few days ago through some random google searches and I've been using it a lot since then. Would hate to see it taken down. Let us know in case you change its location please

**Comment by oO-u-Oo** [comment]
@J05HI 
Upload it to mega and then encrypt it with this page. ;)
https://shurcrypter.se

**Comment by FatKiwi** [comment]
This stuff lasted only 2 months... and it wasn't even famous. His repo and the 10 forks were hit hard.
https://github.com/github/dmca/blob/master/2017/2017-02-06-Deezer.md

Feeling paranoid now... 😕

**Comment by oswaldo-mobray** [comment]
One could also host a git server (or gitlab, gogs, ...) behind a tor hidden service.

**Comment by oO-u-Oo** [comment]
@J05HI
Upload it to mega and then encrypt it with this page. 
https://shurcrypter.se

Check the box "Enmascarar nombres de archivo incluso al descargar" or "Mask file names even when downloading", doing this you will get difficult that deezer will report the real link of the file and the name to mega. ;)

**Comment by MalexTP** [comment]
it's safe, deezloader the developer got tired long ago and still serves

So I think deezloadr will last a long time

**Comment by MalexTP** [comment]
Upload it to npm repositories, there persists deezloader-server

**Comment by fabriccioguzman** [comment]
upload your post here http://je.ro/en/index.php
and the repository upload it to mega, zippyshare, uploaded or other or by ed2k

http://je.ro/en/index.php

**Comment by J05HI** [comment]
Thanks for the many ideas!
I think the only easy way is to host it somewhere else.

Therefore I need to reset this repo. Does anyone know how to do that without loosing stargazers and issues?

**Comment by zouhair** [comment]
https://help.github.com/articles/backing-up-a-repository/

**Comment by troufiniou** [comment]
@J05HI Go to IRC and for the source code make a private GitLab with some people to access on the source code for making modification. Make release on torrent or some website (MEGA, Google Drive)

**Comment by J05HI** [comment]
And what about my Email and PayPal?
Can they do something against me?

**Comment by FatKiwi** [comment]
I was thinking about it, your photo and email are leaked. So they most likely will bother you.

**Comment by RandomNinjaAtk** [comment]
Probably remove the project, start it as a new repo, new name and no references to yourself personally...

**Comment by troufiniou** [comment]
@J05HI Remove Paypal, only BTC they will not find you (with a new wallet for no reference about this adress)

**Comment by troufiniou** [comment]
Oh and if you don't want to be "found" remove in the Metadata the link of your git on your line                 ```
comment:       {
                    text: 'Downloaded from Deezer with DeezLoadr. https://github.com/J05HI/DeezLoadr'
                }
};
```

**Comment by troufiniou** [comment]
Ok so after check (sorry if I'm spam)
- Take a server on Online.net (not expensive or I'm ready to share with you a server if you want)
- Install gitlab on your server https://about.gitlab.com/installation/
- Don't share the IP (only with people you trust), remove robot.txt
- The people who have access on the server will share the soft on MEGA, torrent.

I think it's the best solution

**Comment by tazitus** [comment]
>remove robot.txt

Wouldn't you want a robots.txt that disallows everything? Something like:
```
User-agent: *
Disallow: /
```

I'm not sure what crawlers do when they don't find a robots.txt, but having a prohibitive one is probably better than having none.

**Comment by J05HI** [comment]
Great!!!
Let's see...
Which private messaging do you recommend?

**Comment by troufiniou** [comment]
IRC with auth is one of the best solution. We can use telegram or Signal for "security" and crypted message.

**Comment by J05HI** [comment]
And which IRC client?

**Comment by tazitus** [comment]
The client doesn't really matter. It depends on your OS and preferences.

**Comment by troufiniou** [comment]
Windows you have hexchat
Mac OS you have Textual
Linux IDK but you have a lot of soft
Android AndroIRC

Or KiwiIRC for all browser

**Comment by portableko** [comment]
Upload it on mega, gdrive or bitbucket as they said. Don't post links on reddit. add me on your list too in case that happen (i hope not). Btw i downloaded your build last Nov 27 and still using it by just "repairing" the flac stream.

**Comment by troufiniou** [comment]
@J05HI Send a PM on Reddit or Twitter (Troufiniou) to discuss about server if you need.

**Comment by J05HI** [comment]
@troufiniou
Let's see
I think I'll upload it to Gitlab

**Comment by FatKiwi** [comment]
OK, sounds good. Maybe do a private Gitlab while it's not too famous yet.

**Comment by Starbix** [comment]
[IPFS](https://ipfs.io) may work for this.

btw: I created a dockerimage for deezloadr, it uses a web terminal to interact with deezloadr. You can find it here https://github.com/Starbix/dockerimages/tree/master/deezloadr

**Comment by tabepic** [comment]
@Starbix 
I've read up on IPFS a bit, how exactly do you plan on using it?
To distribute prebuilt binaries?
To host the git repo?

**Comment by MalexTP** [comment]
You can easily make a group on Telegram and upload Deezloadr how a zip

**Comment by J05HI** [comment]
@MalexTP
Yeah but I'm not anonym then

**Comment by MalexTP** [comment]
@J05HI You can hide your phone number and if you want, delete your alias.

**Comment by jonaaa20** [comment]
Well, first of all you shouldn't be using your real photo, about you name, no problems with it, email? Use a "for-work" email, not the real one, The alias, no problems with it, about where to upload it if something goes wrong? Gitlab and Telegram group is a good catch.

**Comment by tabepic** [comment]
In addition to @Starbix's suggestion, [git-remote-ipfs](https://godoc.org/github.com/cryptix/git-remote-ipfs) would be a way to host the git repo over IPFS.

The only issue I can think of is how many people actually use/would use IPFS.
Although this could be worked around by simply using the IPFS git repo as a "mirror" of sorts for the Github repo, and if this gets shut down we move to IPFS and something like [Wire](https://wire.com) for communication.

**Comment by J05HI** [comment]
Can someone setup a repo on ipfs.
I'm a newbie in this 🙄

Is wire 100% secure and anonymous?

**Comment by tabepic** [comment]
@J05HI Sure, I'll setup a git repo.

Wire is very secure, yes.
Annonymous, on the other hand... it's only as annonymous as you make it. You could just signup with an email specifically for this, and create an alias instead of using your real name.

**Comment by J05HI** [comment]
Okay thanks.
Sorry if I can't do this.
Would rather like to improve the app every free minute :)

**Comment by tabepic** [comment]
Well it turns out I was dead wrong.
IPFS is of course read only, which means the git repo would be read only and pretty much useful as just a mirror. 😞 

It looks like we need a better place to host the repo.

**Comment by MalexTP** [comment]
Gitlab looks good, why not?

Use fake email and data.

**Comment by tabepic** [comment]
@MalexTP You do run the risk of Deezer seeing it + taking it down then, right? (Unless you set it as private I guess)

**Comment by MalexTP** [comment]
![image](https://user-images.githubusercontent.com/24663715/33791781-bc514bcc-dc5f-11e7-9dd6-b86777347fb5.png)
@tabepic 11 months repos of deeloader

**Comment by tabepic** [comment]
@MalexTP Well okay then. Didn't know it used to be hosted there.
Sounds great to me. Gitlab + maybe Wire? (Or would Wire be redundant then, idk)

**Comment by J05HI** [comment]
Okay I'll setup the repo on a private gitlab.
Additionally I'll create a telegram group for devs and a channel for the users.
Moreover I'll create a new repo on Github for reporting issues.

**Comment by jonaaa20** [comment]
Gitlab + Telegram group is enough

**Comment by troufiniou** [comment]
I will be happy toi join Dev (I want to learn and why not try to make an UI)

**Comment by tabepic** [comment]
Me too, but I don't have telegram... I'd join the discord though if there is one.

**Comment by troufiniou** [comment]
@tabepic Don't need app or what, exist in web app

**Comment by J05HI** [comment]
Simply create an account :)

**Comment by J05HI** [comment]
Write your telegram usernames here so I can add you to the dev group

**Comment by troufiniou** [comment]
@troufiniou

What else lol

**Comment by jonaaa20** [comment]
My username is @jonaaa20x on telegram

**Comment by FatKiwi** [comment]
@FatKiwi

**Comment by J05HI** [comment]
@jonaaa20  @FatKiwi 
Added :)

**Comment by rafmib** [comment]
@rafmib please :)

**Comment by J05HI** [comment]
@rafmib
You're a dev?

**Comment by MonkeyWrench123** [comment]
@Monkeywrench123 please

**Comment by rafmib** [comment]
i'm mainly .net/C# dev but learning node.js :)

**Comment by Starbix** [comment]
@Starbix

**Comment by troufiniou** [comment]
@j05hi Can you add me too ? :) Thanks

**Comment by J05HI** [comment]
Sure :)
I only need your username

**Comment by J05HI** [comment]
Added you

**Comment by RandomNinjaAtk** [comment]
@J05HI  Username: RandomNinjaAtk on telegram

**Comment by J05HI** [comment]
@RandomNinjaAtk
Added

**Comment by J05HI** [comment]
I close this now because I have all infos :)
Thank you very much for your help!!!

**Comment by taogre** [comment]
@taogre

On Dec 9, 2017 11:34 PM, "Joshua Ott" <notifications@github.com> wrote:

Closed #67 <https://github.com/J05HI/DeezLoadr/issues/67>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/J05HI/DeezLoadr/issues/67#event-1380172400>, or mute
the thread

**Comment by J05HI** [comment]
@taogre
?

**Comment by tazitus** [comment]
Can you also add @tazitus on Telegram?

**Comment by therohanchawla** [comment]
@therohanchawla on telegram...thanks a lot

**Comment by m0rpheaux** [comment]
bro please add @m0rpheaux on telegram, sorry for being a later comer.

**Comment by J05HI** [comment]
@m0rpheaux
You're a developer?

**Comment by m0rpheaux** [comment]
@J05HI I am a graphics designer bro !

**Comment by J05HI** [comment]
@m0rpheaux
Great!
Maybe I'll need you for an icon :)

**Comment by J05HI** [comment]
@m0rpheaux
Added you! :)

**Comment by greenzwiz** [comment]
@greenzwiz telegram. Thanks!

**Comment by greenzwiz** [comment]
I can be a tester. I more do web development etc. 😒

**Comment by J05HI** [comment]
@greenzwiz
We are on Discord now

**Comment by J05HI** [comment]
@greenzwiz
If you're a web developer you could write nodejs apps too :)

**Comment by tazitus** [comment]
> We are on Discord now

How do I join? I just created an account with username tazitus#3393

**Comment by J05HI** [comment]
I'll add you, thx :)

**Comment by J05HI** [comment]
@tazitus
Here: https://discord.gg/aBMZxX

**Comment by tazitus** [comment]
>https://discord.gg/aBMZxX

That link seems to have expired before I could use it.

**Comment by J05HI** [comment]
@tazitus 
https://discord.gg/5nYywZ

**Comment by tabepic** [comment]
@J05HI Can I get an invite for Discord please?

**Comment by RandomNinjaAtk** [comment]
@tabepic https://discord.gg/ndFYS

**Comment by tabepic** [comment]
@RandomNinjaAtk Thanks

**Comment by RandomNinjaAtk** [comment]
@tabepic NP
