### ISSUE TITLE
[Bug] FLAC - No metadata, but has artwork

### ISSUE THREAD

**Issue by RandomNinjaAtk** [J05HI/DeezLoadr#68]
So FLAC metadata tagging is working for most albums/playlists. However, sometimes it will only add the artwork to the Flac files without the metadata... No reported errors, here's an example url:
http://www.deezer.com/us/album/1684280

**Comment by J05HI** [comment]
@RandomNinjaAtk
Okay I'll look at it

**Comment by FatKiwi** [comment]
Nice album :)
Btw, this album comes tagged already (with no artwork). I guess it's conflict when tagging happens (i.e. cannot re-tag properly because the current tagger tags weirdly in header). Just a theory.

**Comment by J05HI** [comment]
Fixed with: [https://github.com/J05HI/DeezLoadr/commit/ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6](https://github.com/J05HI/DeezLoadr/commit/ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6)

I need someone who can add the flac and metaflac binaries for OSX and Linux.

**Comment by J05HI** [comment]
Build and try it now :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
