### ISSUE TITLE
[Question] GUI features

### ISSUE THREAD

**Issue by tabepic** [J05HI/DeezLoadr#69]
What can we expect for the GUI in terms of features?

Would it be more like Deezloader, where you can search tracks, top lists, albums, and playlists in the program?
Or would it stay more like it is right now (maybe with some options however)?

Not trying to be pushy, but I'd like to know whether to keep developing my seperate version of Deezloader 😃

**Comment by J05HI** [comment]
Some things I've planned for the future:
• Nice user interface
• Download path selection
• Filename configuration (with variables)
• Something like a playlist/artist watcher which checks a playlist/artist in a defined cycle and downloads new tracks
• Artist/Album/Playlist search
• List of most popular songs by country
• ...

**Comment by J05HI** [comment]
No need to develop your own version.
Would be really nice if you help here :)
I'm really open for pull request

**Comment by MalexTP** [comment]
Search and preview songs? Is possible?

**Comment by J05HI** [comment]
@MalexTP 
You mean the 30sec preview?

**Comment by MalexTP** [comment]
@J05HI Yes, or play song at 128kbps

**Comment by J05HI** [comment]
@MalexTP 
Yeah I can add this

**Comment by tabepic** [comment]
@J05HI Okay, sounds good.
I'm not much of a js dev, but I'll try help out here and there.

**Comment by J05HI** [comment]
@tabepic
Okay great!

**Comment by tabepic** [comment]
I guess I'll close this issue then, now that I have the answers I was looking for

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
