### ISSUE TITLE
256 kbps not available?

### ISSUE THREAD

**Issue by tabepic** [J05HI/DeezLoadr#73]
I can see in the musicQualities that 256 is there, but it's not in the choices, is there a reason for this? Or was it just omitted for now until more pressing issues are dealt with?

**Comment by J05HI** [comment]
@tabepic
I haven't added it because no song I've seen is available in it

**Comment by tabepic** [comment]
Oh okay. I'll add it and make a pull req if that's okay.

**Comment by J05HI** [comment]
Yeah you could do that if you like :)
Don't forget to add 265 to getValidTrackQuality()

**Comment by tabepic** [comment]
Will do, I'll use that path (for now anyways)

**Comment by J05HI** [comment]
Maybe I'll add an converter in the future.

**Comment by mudlord** [comment]
Though if you do, convert from the FLAC download though. Lossy compressing already lossy tracks (like the 320kbps downloads) is bad.

**Comment by J05HI** [comment]
@mudlord
Yeah I'll do so.
But downloading and converting a song will take some time then.

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
