### ISSUE TITLE
API timeout

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#77]
When you leave app open for more than 1 hour without usage.

![snap12](https://user-images.githubusercontent.com/9163913/33800760-f0339906-dd3e-11e7-82ef-3a1c0acff30e.png)

**Comment by J05HI** [comment]
@FatKiwi 
I think this must have something to do with the api key.
Maybe it's only valid for 1 hour.

**Comment by FatKiwi** [comment]
You are right, it happens with Athame too. Maybe reinitialize after 1 hour or something?

**Comment by J05HI** [comment]
@FatKiwi 
Yeah I'll do that

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
