### ISSUE TITLE
Add config.json file

### ISSUE THREAD

**Issue by MonkeyWrench123** [J05HI/DeezLoadr#78]
Create a config.json file to help change settings in future

**Comment by J05HI** [comment]
@MonkeyWrench123 
Duplicate: [https://github.com/J05HI/DeezLoadr/issues/21](https://github.com/J05HI/DeezLoadr/issues/21)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
