### ISSUE TITLE
[Question] CLI support

### ISSUE THREAD

**Issue by tabepic** [J05HI/DeezLoadr#79]
I realize that there are some features planned for when the GUI is created (searching for tracks/albums/artists, converting to other music formats, etc).
When the GUI is done, will the CLI get these features as well? Will the CLI be abandoned?

**Comment by J05HI** [comment]
@tabepic
Maybe I'll add this features to the cli too :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
