### ISSUE TITLE
Missing metadata for FLAC

### ISSUE THREAD

**Issue by azgul** [J05HI/DeezLoadr#8]
For example http://www.deezer.com/en/album/139617

The ones that has missing metadata has `<ENCODER>` set to `Lavf55.40.100`. Whereas the ones where it works has nothing for that tag and instead has `ENCODING SETTINGS=DeezLoadr`

**Comment by J05HI** [comment]
@azgul
Sorry I don't know what you really mean.
Could you please describe it better :)

**Comment by azgul** [comment]
Try downloading the mentioned album in FLAC. It won't have id3 tags. I'll
try to debug it later. It looks like there is a big try catch in the code
that handles it, so if anything fails it won't write any tags

**Comment by J05HI** [comment]
@azgul
Oh now I got it!
You're downloading in flac.
Yeah that's a problem. The tags come from Deezer not me. I don't know how to write id3 tags to flac files. The used lib somehow can't handle it :(

**Comment by azgul** [comment]
It works for some albums. I'll provide examples when I'm home

**Comment by J05HI** [comment]
@azgul
Okay thank you!

**Comment by azgul** [comment]
http://www.deezer.com/en/album/14564486
this album has id3 tags for both mp3 and FLAC

http://www.deezer.com/en/album/139617
but this album only gets the id3 tags written for mp3

**Comment by azgul** [comment]
The Goon Bap album is fine:
```
$ ffprobe "DOWNLOADS/Snowgoons/Goon Bap/01 Kick Snare & Hi-Hats Intro.flac"
ffprobe version N-87286-g6ce4a63 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/home/plex/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/plex/ffmpeg_build/include --extra-ldflags=-L/home/plex/ffmpeg_build/lib --bindir=/home/plex/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-gpl --enable-version3 --enable-libwebp --cpu=native --enable-vaapi --enable-openssl
  libavutil      55. 74.100 / 55. 74.100
  libavcodec     57.105.100 / 57.105.100
  libavformat    57. 82.100 / 57. 82.100
  libavdevice    57.  8.100 / 57.  8.100
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, flac, from 'DOWNLOADS/Snowgoons/Goon Bap/01 Kick Snare & Hi-Hats Intro.flac':
  Metadata:
    title           : Kick, Snare & Hi-Hats Intro
    artist          : Snowgoons, Dj Premier
    album           : Goon Bap
    copyright       : (c) 2016 Goon MuSick
    album_artist    : Snowgoons
    track           : 1
    disc            : 1
    TSRC            : DELJ81622172
    encoder         : DeezLoadr
    comment         : Downloaded from Deezer with DeezLoadr. https://github.com/J05HI/DeezLoadr
    composer        : Snowgoons
    date            : 2016
  Duration: 00:01:08.41, start: 0.000000, bitrate: 876 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
```

But the Black Snow album has no tags:
```
$ ffprobe "DOWNLOADS/Snowgoons/Black Snow/01 The Curse.flac"
ffprobe version N-87286-g6ce4a63 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/home/plex/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/plex/ffmpeg_build/include --extra-ldflags=-L/home/plex/ffmpeg_build/lib --bindir=/home/plex/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-gpl --enable-version3 --enable-libwebp --cpu=native --enable-vaapi --enable-openssl
  libavutil      55. 74.100 / 55. 74.100
  libavcodec     57.105.100 / 57.105.100
  libavformat    57. 82.100 / 57. 82.100
  libavdevice    57.  8.100 / 57.  8.100
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
[flac @ 0x2dcbd40] Discarding ID3 tags because more suitable tags were found.
Input #0, flac, from 'DOWNLOADS/Snowgoons/Black Snow/01 The Curse.flac':
  Metadata:
    ENCODER         : Lavf55.42.100
  Duration: 00:03:56.75, start: 0.000000, bitrate: 1007 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
```

**Comment by azgul** [comment]
https://github.com/J05HI/DeezLoadr/issues/12#issuecomment-346938744 I tried with `taglib2` instead of `node-id3` and that works for [Snowgoons - Black Snow](http://www.deezer.com/en/album/139617), but it only supports the following id3 tags: album, artist, comment, date, title

**Comment by J05HI** [comment]
@azgul
Okay I'll give it a try :)

**Comment by kingofwap** [comment]
same here missing tags for Flac.

**Comment by tazitus** [comment]
>I don't know how to write id3 tags to flac files. The used lib somehow can't handle it :(

That's because you're not supposed to do it.


> FLAC has it's own native tagging system which is identical to that of Vorbis. They are called alternately "FLAC tags" and "Vorbis comments". It is the only tagging system required and guaranteed to be supported by FLAC implementations.
> 
> Out of convenience, the reference decoder knows how to skip ID3 tags so that they don't interfere with decoding. But you should not expect any tags beside FLAC tags to be supported in applications; some implementations may not even be able to decode a FLAC file with ID3 tags.
- https://xiph.org/flac/faq.html

**Comment by RandomNinjaAtk** [comment]
Really need this now that flac is working!

**Comment by J05HI** [comment]
@RandomNinjaAtk
Hopefully this weekend :)

**Comment by arbingordon** [comment]
How far are you into supporting this?
I broke the tag function into two separate ones (one for mp3, one for flac), I have it writing metadata right now - but the ffmetadata lib doesn't support writing images to flac (but does support writing them to mp3).

I can try and clean it up a bit and submit a PR if you'd like?
Just figuring your talent might be better spent on some of the presumably harder to solve bugs right now.

**Comment by RandomNinjaAtk** [comment]
@arbingordon 
I'd be okay with having the app just save a copy of the Album Art (Cover Art) as folder.jpg in the root of the album folder, you could then easily use MP3Tag or other programs to import it, if desired...

**Comment by arbingordon** [comment]
Yea, external album art is my personal preference too.

That's not really an issue though, if we wanted, we could use https://github.com/melchor629/node-flac-bindings to handle the flac meta reading/writing.  This library, I believe, supports embedding cover art just fine.
Shame there isn't a common lib that can abstract those things away for us.

**Comment by J05HI** [comment]
@arbingordon

Great to hear!
Pull request are always welcome!!! :)
Does this lib really don't support cover arts :(

Yeah I could do that but I don't want to implement it dirty.
It'll work :)

**Comment by arbingordon** [comment]
@J05HI 
One thing I've noticed, some tracks are pretagged directly off the CDN, eg:
http://www.deezer.com/us/track/138546539
I think most songs aren't tagged - how do you want to handle that?
I have tags+album art writing working w/  https://github.com/melchor629/node-flac-bindings currently.

**Comment by J05HI** [comment]
@arbingordon
Overwrite them :)

**Comment by J05HI** [comment]
@arbingordon 
Create a pull request if you're ready

**Comment by arbingordon** [comment]
I will when I clean this up a bit - I don't do much in JS so it's harder to write clean code for it.  Figure I'll have a PR for you in the next day or so if nothing comes up.

Aside - have you considered downloading HQ album art off their CDN? I think at minimum they host 1200x1200 PNGs, though I've found some as large as 4000x4000! ( https://e-cdns-images.dzcdn.net/images/cover/b6b04e0970de9e6f43fae19aabf72c13/4000x4000.png )

**Comment by RandomNinjaAtk** [comment]
4000x4000 would be great!

**Comment by J05HI** [comment]
@arbingordon
Keep it 500x500.
I'll make it configurable in v1.3.0 :)

**Comment by RandomNinjaAtk** [comment]
@J05HI 

When displaying artwork on a 4k tv or in the future 8k/10k, the higher the quality, the better it will look. 4000x4000 is likely over kill... but if I have the option, I like to future proof...

**Comment by J05HI** [comment]
@RandomNinjaAtk
Yeah I'll add it. So everyone can choose it.

**Comment by J05HI** [comment]
@RandomNinjaAtk @arbingordon @tazitus @azgul 

Implemented with [https://github.com/J05HI/DeezLoadr/commit/f33659c87a1e6e7bd9acdac75fff88eebb55607b](https://github.com/J05HI/DeezLoadr/commit/f33659c87a1e6e7bd9acdac75fff88eebb55607b)

**Comment by RandomNinjaAtk** [comment]
@J05HI 
So I just tested the new build and it works, but when looking at the tags in MP3TAG it seems to written all tags twice, heres an example:
![capture](https://user-images.githubusercontent.com/8386416/33573670-86ca205e-d904-11e7-9826-deafaff9ec0f.PNG)

**Comment by J05HI** [comment]
@RandomNinjaAtk 
Okay strange...
Will fix this tomorrow. It's working for now.

**Comment by J05HI** [comment]
Closed because of [https://github.com/J05HI/DeezLoadr/issues/61](https://github.com/J05HI/DeezLoadr/issues/61)
