### ISSUE TITLE
Fill ALBUMARTIST Tag

### ISSUE THREAD

**Issue by rafmib** [J05HI/DeezLoadr#81]
Could you please also fill the ALBUMARTIST tag ?

trackInfos.ALB_ART_NAM & '--set-tag=ALBUMARTIST='

**Comment by J05HI** [comment]
For flac?
It should already do this

**Comment by rafmib** [comment]
yes, for FLAC.

You don't have the line 
"--set-tag=ALBUMARTIST=" on "let metaflacInstance.."

**Comment by J05HI** [comment]
There is no albumartist in flac, it is named performer

**Comment by rafmib** [comment]
oh really? that's weird, on MP3TAG it's displayed as "Album Artist"and so it's always empty.
So "Performer" is the offical property for the album artist tag for Flac files?

**Comment by J05HI** [comment]
Strange, I'll look at it

**Comment by J05HI** [comment]
Build and try it now :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
