### ISSUE TITLE
FLAC - Incorrect Album Year tag

### ISSUE THREAD

**Issue by rafmib** [J05HI/DeezLoadr#82]
I don't know if it's due to Deezer but often, the Album Year tag info is incorrect.

Ex: with U2 - Achtung Baby (http://www.deezer.com/fr/album/1316058).
It was initially released in 1991 but it gets tagged 2011.

Or Guns N' Roses - The Spaghetti Incident (http://www.deezer.com/fr/album/12452298)
Released in 1993 but tagged 2016 :(

Isn't there a way to fetch the correct Album's year ? (COPYRIGHT or PUBLISHER tags maybe?)

**Comment by tazitus** [comment]
Those should be correct. Albums are often released multiple times. The one on Deezer is probably just one newer release.
You can see the releases and dates for your first example [here](https://musicbrainz.org/release-group/744c7a1b-ac79-35c4-bd92-7e2c6a24c8d8) for instance.

**Comment by rafmib** [comment]
Yes « correct » as a strict « cd release date from edition xx”.
But would there be a possibility of getting the album official release date as listed on musicbrainz’s page for your example: 18 November 1991

**Comment by tazitus** [comment]
I don't think so. http://api.deezer.com/album/1316058 doesn't seem to provide the original release date.

**Comment by rafmib** [comment]
ok thank you for looking :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
