### ISSUE TITLE
Add all flac & metaflac binaries

### ISSUE THREAD

**Issue by J05HI** [J05HI/DeezLoadr#83]
- [x] Windows x64
- [x] Windows x86
- [x] Linux x64
- [x] Linux x86
- [x] MacOS x64

**Comment by tabepic** [comment]
I can build 32-bit binaries as well, might take a couple of hours to setup though.

**Comment by tabepic** [comment]
That didn't take long; here they are: [https://ptpb.pw/jn2_.zip](https://ptpb.pw/jn2_.zip)

**Comment by J05HI** [comment]
@tabepic 
Amazing thanks!!!
