### ISSUE TITLE
Loadr doesnt finish after Downloads (no new url input possible)

### ISSUE THREAD

**Issue by throwfil** [J05HI/DeezLoadr#85]
When it finishes a album-download (all files fully downloaded) I cant enter another url; looks like it is stuck with finishing up the last batch.

Wasnt an issue with a build before yesterday.

edit
Out of 10 tries, I was able to enter a new url once.

edit2
It seems like when it doesn't finish properly, it doesn't write tags into the files.

**Comment by troufiniou** [comment]
Confirmed problem !

**Comment by FatKiwi** [comment]
Yes, can confirm this.

**Comment by J05HI** [comment]
Okay will look at it :)

**Comment by painlessjeff** [comment]
Well it is working correctly on my side for MP3 and FLAC (btw, thanks for fixing FLAC tagging :-)  ). Arch Linux x64 NodeJS version 9.2.1 if this matters.

**Comment by FatKiwi** [comment]
the last build from 18 hours ago has the bug

**Comment by J05HI** [comment]
@painlessjeff @FatKiwi 
Try now with latest build :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
