### ISSUE TITLE
Not all file are tagged (FLAC issue)

### ISSUE THREAD

**Issue by painlessjeff** [J05HI/DeezLoadr#86]
I just saw when importing in beets some downloaded songs that were not tagged. So I redownloaded them and realized that not all files are tagged and that each redownload tags different files. The behaviour seems random and to only affect FLAC files.

**Comment by tabepic** [comment]
Operating system, 64 or 32bit, node version, and most importantly what commit please (this should be mandatory in my opinion for any bug report). Just to help speed troubleshooting along.

**Comment by painlessjeff** [comment]
Arch Linux x64 Node 9.2.1 and latest commit.

**Comment by tabepic** [comment]
Oh and BTW if you're still on 1.2.0 that version doesn't have the FLAC fixes.

**Comment by painlessjeff** [comment]
I build the binaries myself. Even the .js file has the same behaviour

**Comment by J05HI** [comment]
@painlessjeff
Could you please give examples

**Comment by painlessjeff** [comment]
Here are the test results 
Flac test 1 
![test1](https://user-images.githubusercontent.com/23583260/33843375-2edca3d2-de6b-11e7-9888-a1fd18a4189a.png)

Flac test 2 
![test2](https://user-images.githubusercontent.com/23583260/33843378-3299efca-de6b-11e7-9fb4-58b1bfdc2307.png)

**Comment by J05HI** [comment]
@painlessjeff
Do you have a link please :)

**Comment by painlessjeff** [comment]
Yeah sure. Sorry about that. http://www.deezer.com/album/51457002

**Comment by J05HI** [comment]
Thanks!

**Comment by J05HI** [comment]
@painlessjeff 

Can't replicate it with the latest build:

<img width="520" alt="deezloadr-win-x64_2017-12-12_21-21-03" src="https://user-images.githubusercontent.com/16399787/33906607-b43e7ec0-df82-11e7-9c05-45784df533b4.png">

<img width="1883" alt="2017-12-12_21-22-21" src="https://user-images.githubusercontent.com/16399787/33906608-b6acd99a-df82-11e7-904a-39c701cbac57.png">

**Comment by painlessjeff** [comment]
That's weird. Anyone on linux having this bug? I'll double check everything but thanks anyway! Really nice software anyway

**Comment by J05HI** [comment]
@painlessjeff
It's only on Linux? 64bit?

**Comment by tabepic** [comment]
Just tested on Arch Linux x64 with NodeJS 9.2.1, commit c52828617bf35a29a95e0e7eff585b27bb49485a.
It worked fine, all files tagged properly.

**Comment by FatKiwi** [comment]
Tried with KDE Neon x64. Only one time I got MD5 mismatch and file wasn't tagged (I guess due to bad connection). Worked on 2nd try.

**Comment by painlessjeff** [comment]
Well thanks anyway guys

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
