### ISSUE TITLE
Remove already tagged deezer album arts in FLACs before tagging

### ISSUE THREAD

**Issue by rafmib** [J05HI/DeezLoadr#89]
ex: http://www.deezer.com/fr/album/956676

300x300px and 1000x1000px versions are both downloaded

**Comment by J05HI** [comment]
@rafmib
Lol how
I definitely download it only once

**Comment by rafmib** [comment]
lol haven't looked at code yet but it's was MP3Tag is showing:

![image](https://user-images.githubusercontent.com/25956600/33956944-7ad1fd1a-e040-11e7-9cb0-2fabd016ec13.png)

**Comment by J05HI** [comment]
Oh okay there
Maybe because of deezer is shipping the 300x300 already

**Comment by J05HI** [comment]
@rafmib 
Can confirm it 
It has the cover already from Deezer.
Will remove it now and readd the 1000x1000 then :)

**Comment by J05HI** [comment]
@rafmib 
Fixed :)

**Comment by rafmib** [comment]
thank you :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
